#! /bin/sh

sxhkd &
picom -f &
feh --bg-fill ~/Pictures/w32.png &
~/.config/polybar/p.sh &
#xfce4-power-manager & //brightnessctl
#volumeicon & //pulsemixer
#nm-applet &
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources
#wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true
bspc config directional_focus_tightness low

